# Generated by Django 4.1.7 on 2023-03-08 05:51

from django.db import migrations, models
import imggallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('imggallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(upload_to=imggallery.models.uplode_path),
        ),
    ]
