# Generated by Django 4.1.7 on 2023-03-08 05:53

from django.db import migrations, models
import imggallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('imggallery', '0002_alter_gallery_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=imggallery.models.uplode_path),
        ),
    ]
